"""
Weekly digest generator.
Reads data/feed.json and writes WEEKLY_DIGEST.md.
Run by the digest.yml GitHub Action every Monday at 08:00 UTC.
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path

FEED_PATH = Path(__file__).parent.parent / "data" / "feed.json"
DIGEST_PATH = Path(__file__).parent.parent / "WEEKLY_DIGEST.md"
TOP_N = 5  # items per category in digest


def generate() -> str:
    data = json.loads(FEED_PATH.read_text())
    now = datetime.now(UTC)
    week = now.strftime("Week of %B %d, %Y")

    # Group by category
    by_category: dict[str, list[dict]] = defaultdict(list)
    for item in data:
        by_category[item["category"]].append(item)

    # Sort each category by relevance desc
    for cat in by_category:
        by_category[cat].sort(key=lambda i: i.get("relevance", 0), reverse=True)

    category_order = ["model", "tool", "framework", "repo", "paper", "news"]
    category_emoji = {
        "model": "🤖",
        "tool": "🔧",
        "framework": "🏗️",
        "repo": "📦",
        "paper": "📄",
        "news": "📰",
        "unknown": "🔍",
    }

    lines = [
        f"# AI Ecosystem Radar — {week}",
        "",
        "> Auto-generated by [ai-ecosystem-radar](https://github.com/your-org/ai-ecosystem-radar) "
        f"on {now.strftime('%Y-%m-%d %H:%M')} UTC.",
        "",
        "---",
        "",
    ]

    # Hot section — top 3 trending regardless of category
    hot_items = [i for i in data if i.get("hot") == "hot"][:3]
    if hot_items:
        lines += ["## 🔥 Trending this week", ""]
        for item in hot_items:
            stars = f" ★{item['stars']:,}" if item.get("stars") else ""
            breaking = " ⚠️ **breaking change**" if item.get("breaking") else ""
            lines.append(f"- **[{item['title']}]({item['url']})**{stars}{breaking}")
            lines.append(f"  {item['summary']}")
            lines.append("")

    lines += ["---", ""]

    for cat in category_order:
        items = by_category.get(cat, [])[:TOP_N]
        if not items:
            continue
        emoji = category_emoji.get(cat, "•")
        lines += [f"## {emoji} {cat.capitalize()}s", ""]
        for item in items:
            stars = f" ★{item['stars']:,}" if item.get("stars") else ""
            breaking = " ⚠️ **breaking**" if item.get("breaking") else ""
            source = f"`{item.get('source', '').replace('_', ' ')}`"
            lines.append(f"- **[{item['title']}]({item['url']})**{stars}{breaking} — {source}")
            lines.append(f"  {item['summary']}")
            lines.append("")

    lines += [
        "---",
        "",
        f"*{len(data)} items tracked this week across "
        f"{len(set(i['source'] for i in data))} sources.*",
        "",
        "[Subscribe via GitHub Watch](https://github.com/your-org/ai-ecosystem-radar/subscription) "
        "to get this digest in your inbox every Monday.",
    ]

    return "\n".join(lines)


if __name__ == "__main__":
    digest = generate()
    DIGEST_PATH.write_text(digest)
    print(f"[digest] written to {DIGEST_PATH}")
    print(digest[:500])
